package com.zkingsoft.model.web;

import com.zkingsoft.anotations.Extend;
import java.io.Serializable;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-01 10:36
 */
public class WebArticleType implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  artTypeId;
			
	
	/**
	 * 文章类型名称
	 */
	private String  artTypeName;
			
	
	/**
	 * 父级id
	 */
	private Long  artTypeParentId;
			
	
	/**
	 * 排序
	 */
	private Integer  artTypeSort;
			
	
	/**
	 * 文章类型描叙
	 */
	private String  artTypeDescription;
			
	
	/**
	 * 链接地址
	 */
	private String  artTypeUrl;
			
	
	/**
	 * 图标
	 */
	private String  artTypeIcon;
			
	
	/**
	 * 预留字段（文章类型）
	 */
	private String  artType;
			
	

	public Long getArtTypeId() {
		return artTypeId;
	}
   	
   	public void setArtTypeId(Long artTypeId) {
		this.artTypeId=artTypeId;
	}
   	

	public String getArtTypeName() {
		return artTypeName;
	}
   	
   	public void setArtTypeName(String artTypeName) {
		this.artTypeName=artTypeName;
	}
   	

	public Long getArtTypeParentId() {
		return artTypeParentId;
	}
   	
   	public void setArtTypeParentId(Long artTypeParentId) {
		this.artTypeParentId=artTypeParentId;
	}
   	

	public Integer getArtTypeSort() {
		return artTypeSort;
	}
   	
   	public void setArtTypeSort(Integer artTypeSort) {
		this.artTypeSort=artTypeSort;
	}
   	

	public String getArtTypeDescription() {
		return artTypeDescription;
	}
   	
   	public void setArtTypeDescription(String artTypeDescription) {
		this.artTypeDescription=artTypeDescription;
	}
   	

	public String getArtTypeUrl() {
		return artTypeUrl;
	}
   	
   	public void setArtTypeUrl(String artTypeUrl) {
		this.artTypeUrl=artTypeUrl;
	}
   	

	public String getArtTypeIcon() {
		return artTypeIcon;
	}
   	
   	public void setArtTypeIcon(String artTypeIcon) {
		this.artTypeIcon=artTypeIcon;
	}
   	

	public String getArtType() {
		return artType;
	}
   	
   	public void setArtType(String artType) {
		this.artType=artType;
	}
   	

	@Override
	public String toString() {
		return "{WebArticleType:{"
		+"artTypeId:"+artTypeId+","
		+"artTypeName:"+artTypeName+","
		+"artTypeParentId:"+artTypeParentId+","
		+"artTypeSort:"+artTypeSort+","
		+"artTypeDescription:"+artTypeDescription+","
		+"artTypeUrl:"+artTypeUrl+","
		+"artTypeIcon:"+artTypeIcon+","
		+"artType:"+artType+","
		+"}}";
	}


  
}