package com.zkingsoft.model.web;

import com.zkingsoft.anotations.Extend;
import java.io.Serializable;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-28 15:35
 */
public class WebNav implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  navId;
			
	
	/**
	 * 导航名称
	 */
	private String  navName;
			
	
	/**
	 * 父级导航
	 */
	private Long  parentId;
			
	
	/**
	 * 导航等级
	 */
	private Integer  navGrade;
			
	
	/**
	 * 链接地址
	 */
	private String  navUrl;
			
	
	/**
	 * 图标
	 */
	private String  navInco;
			
	
	/**
	 * 描述
	 */
	private String  navDescription;
			
	
	/**
	 * 类型
	 */
	private String  navType;
			
	
	/**
	 * 所属平台
	 */
	private Integer  navPlat;
			
	
	private Long  companyId;
			
	
	private Integer  navOrderby;
			
	

	public Long getNavId() {
		return navId;
	}
   	
   	public void setNavId(Long navId) {
		this.navId=navId;
	}
   	

	public String getNavName() {
		return navName;
	}
   	
   	public void setNavName(String navName) {
		this.navName=navName;
	}
   	

	public Long getParentId() {
		return parentId;
	}
   	
   	public void setParentId(Long parentId) {
		this.parentId=parentId;
	}
   	

	public Integer getNavGrade() {
		return navGrade;
	}
   	
   	public void setNavGrade(Integer navGrade) {
		this.navGrade=navGrade;
	}
   	

	public String getNavUrl() {
		return navUrl;
	}
   	
   	public void setNavUrl(String navUrl) {
		this.navUrl=navUrl;
	}
   	

	public String getNavInco() {
		return navInco;
	}
   	
   	public void setNavInco(String navInco) {
		this.navInco=navInco;
	}
   	

	public String getNavDescription() {
		return navDescription;
	}
   	
   	public void setNavDescription(String navDescription) {
		this.navDescription=navDescription;
	}
   	

	public String getNavType() {
		return navType;
	}
   	
   	public void setNavType(String navType) {
		this.navType=navType;
	}
   	

	public Integer getNavPlat() {
		return navPlat;
	}
   	
   	public void setNavPlat(Integer navPlat) {
		this.navPlat=navPlat;
	}
   	

	public Long getCompanyId() {
		return companyId;
	}
   	
   	public void setCompanyId(Long companyId) {
		this.companyId=companyId;
	}
   	

	public Integer getNavOrderby() {
		return navOrderby;
	}
   	
   	public void setNavOrderby(Integer navOrderby) {
		this.navOrderby=navOrderby;
	}
   	

	@Override
	public String toString() {
		return "{WebNav:{"
		+"navId:"+navId+","
		+"navName:"+navName+","
		+"parentId:"+parentId+","
		+"navGrade:"+navGrade+","
		+"navUrl:"+navUrl+","
		+"navInco:"+navInco+","
		+"navDescription:"+navDescription+","
		+"navType:"+navType+","
		+"navPlat:"+navPlat+","
		+"companyId:"+companyId+","
		+"navOrderby:"+navOrderby+","
		+"}}";
	}


  
}