package com.zkingsoft.services.sys;

import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysBtn;
import java.util.List;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
public interface SysBtnService  extends BaseServices<SysBtn>{
	
	/**
	 * 新增SysBtn
	 * 
	 */
	public int add(SysBtn sysBtn);
   	
   	/**
	 * 批量新增SysBtn
	 * 
	 */
	public int batchAdd(List<SysBtn>  sysBtnList);
   	
   	/**
	 * 根据map键值对 更新SysBtn
	 * 
	 */
	public int modifyByMap(SysBtn oldSysBtn ,SysBtn newSysBtn);
	
	/**
	 * 根据对象 更新SysBtn
	 * 
	 */
	public int modifyByModel(SysBtn sysBtn);
	
	/**
	 * 批量删除SysBtn
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除SysBtn
	 * 
	 */
	public int removeById(Long id);
	
	/**
	 * 根据对象删除SysBtn
	 * 
	 */
	public int removeByModel(SysBtn sysBtn);
	
	/**
	 * 分页查询SysBtn
	 * 
	 */
	public List<SysBtn> findInPage(SysBtn sysBtn, PaginationVO pageVo);

	/**
	 * 根据对象查询SysBtn
	 * 
	 */
	public List<SysBtn> findByModel(SysBtn sysBtn);
	
	/**
	 * 统计记录数SysBtn
	 * 
	 */
	public int  findTotal(SysBtn sysBtn);
	
	/**
	 * 根据id查询SysBtn
	 * 
	 */
	public SysBtn  findById(Long id);

   	

  
}