package com.zkingsoft.services.sys;

import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysCompany;
import java.util.List;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
public interface SysCompanyService  extends BaseServices<SysCompany>{
	
	/**
	 * 新增SysCompany
	 * 
	 */
	public int add(SysCompany sysCompany);
   	
   	/**
	 * 批量新增SysCompany
	 * 
	 */
	public int batchAdd(List<SysCompany>  sysCompanyList);
   	
   	/**
	 *  更新公司和公司下所有员工的权限
	 * 
	 */
	public int modifyByMap(SysCompany oldSysCompany ,SysCompany newSysCompany);
	
	/**
	 * 根据对象 更新SysCompany
	 * 
	 */
	public int modifyByModel(SysCompany sysCompany);
	
	/**
	 * 批量删除SysCompany
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除SysCompany
	 * 
	 */
	public int removeById(Long comId);
	
	/**
	 * 根据对象删除SysCompany
	 * 
	 */
	public int removeByModel(SysCompany sysCompany);
	
	/**
	 * 分页查询SysCompany
	 * 
	 */
	public List<SysCompany> findInPage(SysCompany sysCompany, PaginationVO pageVo);

	/**
	 * 根据对象查询SysCompany
	 * 
	 */
	public List<SysCompany> findByModel(SysCompany sysCompany);
	
	/**
	 * 统计记录数SysCompany
	 * 
	 */
	public int  findTotal(SysCompany sysCompany);
	
	/**
	 * 根据id查询SysCompany
	 * 
	 */
	public SysCompany  findById(Long comId);

   	

  
}