package com.zkingsoft.services.sys;

import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysDataDictionary;
import java.util.List;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
public interface SysDataDictionaryService  extends BaseServices<SysDataDictionary>{
	
	/**
	 * 新增SysDataDictionary
	 * 
	 */
	public int add(SysDataDictionary sysDataDictionary);
   	
   	/**
	 * 批量新增SysDataDictionary
	 * 
	 */
	public int batchAdd(List<SysDataDictionary>  sysDataDictionaryList);
   	
   	/**
	 * 根据map键值对 更新SysDataDictionary
	 * 
	 */
	public int modifyByMap(SysDataDictionary oldSysDataDictionary ,SysDataDictionary newSysDataDictionary);
	
	/**
	 * 根据对象 更新SysDataDictionary
	 * 
	 */
	public int modifyByModel(SysDataDictionary sysDataDictionary);
	
	/**
	 * 批量删除SysDataDictionary
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除SysDataDictionary
	 * 
	 */
	public int removeById(Long dicId);
	
	/**
	 * 根据对象删除SysDataDictionary
	 * 
	 */
	public int removeByModel(SysDataDictionary sysDataDictionary);
	
	/**
	 * 分页查询SysDataDictionary
	 * 
	 */
	public List<SysDataDictionary> findInPage(SysDataDictionary sysDataDictionary, PaginationVO pageVo);

	/**
	 * 根据对象查询SysDataDictionary
	 * 
	 */
	public List<SysDataDictionary> findByModel(SysDataDictionary sysDataDictionary);
	
	/**
	 * 统计记录数SysDataDictionary
	 * 
	 */
	public int  findTotal(SysDataDictionary sysDataDictionary);
	
	/**
	 * 根据id查询SysDataDictionary
	 * 
	 */
	public SysDataDictionary  findById(Long dicId);

   	

  
}