package com.zkingsoft.services.sys;

import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysFunction;
import java.util.List;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
public interface SysFunctionService  extends BaseServices<SysFunction>{
	
	/**
	 * 新增SysFunction
	 * 
	 */
	public int add(SysFunction sysFunction);
   	
   	/**
	 * 批量新增SysFunction
	 * 
	 */
	public int batchAdd(List<SysFunction>  sysFunctionList);
   	
   	/**
	 * 根据map键值对 更新SysFunction
	 * 
	 */
	public int modifyByMap(SysFunction oldSysFunction ,SysFunction newSysFunction);
	
	/**
	 * 根据对象 更新SysFunction
	 * 
	 */
	public int modifyByModel(SysFunction sysFunction);
	
	/**
	 * 批量删除SysFunction
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除SysFunction
	 * 
	 */
	public int removeById(Long fnId);
	
	/**
	 * 根据对象删除SysFunction
	 * 
	 */
	public int removeByModel(SysFunction sysFunction);
	
	/**
	 * 分页查询SysFunction
	 * 
	 */
	public List<SysFunction> findInPage(SysFunction sysFunction, PaginationVO pageVo);

	/**
	 * 根据对象查询SysFunction
	 * 
	 */
	public List<SysFunction> findByModel(SysFunction sysFunction);
	
	/**
	 * 统计记录数SysFunction
	 * 
	 */
	public int  findTotal(SysFunction sysFunction);
	
	/**
	 * 根据id查询SysFunction
	 * 
	 */
	public SysFunction  findById(Long fnId);

	/**
	 * 启用或者禁用功能
	 * @param fnId
	 * @param status
	 */
	public void setIsDisable(Long fnId, String status);
	
	/**
	 * 查询公司所有的功能权限
	 * @param companyId
	 * @return
	 */
	public List<SysFunction> findCompanyFunction(Long companyId);

	public List<SysFunction> findFunctionByRoleIds(String roleIds);
	/**
	 * 获取当前公司所拥有的权限树，包括按钮
	 * @param id
	 * @return
	 */
	public List<SysFunction> findRoleFuntion(Long id);

   	

  
}