package com.zkingsoft.services.sys;

import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysCompany;
import com.zkingsoft.model.sys.SysPlat;
import java.util.List;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
public interface SysPlatService  extends BaseServices<SysPlat>{
	
	/**
	 * 新增SysPlat
	 * 
	 */
	public int add(SysPlat sysPlat);
   	
   	/**
	 * 批量新增SysPlat
	 * 
	 */
	public int batchAdd(List<SysPlat>  sysPlatList);
   	
   	/**
	 * 根据map键值对 更新SysPlat
	 * 
	 */
	public int modifyByMap(SysPlat oldSysPlat ,SysPlat newSysPlat);
	
	/**
	 * 根据对象 更新SysPlat
	 * 
	 */
	public int modifyByModel(SysPlat sysPlat);
	
	/**
	 * 批量删除SysPlat
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除SysPlat
	 * 
	 */
	public int removeById(Long platId);
	
	/**
	 * 根据对象删除SysPlat
	 * 
	 */
	public int removeByModel(SysPlat sysPlat);
	
	/**
	 * 分页查询SysPlat
	 * 
	 */
	public List<SysPlat> findInPage(SysPlat sysPlat, PaginationVO pageVo);

	/**
	 * 根据对象查询SysPlat
	 * 
	 */
	public List<SysPlat> findByModel(SysPlat sysPlat);
	
	/**
	 * 统计记录数SysPlat
	 * 
	 */
	public int  findTotal(SysPlat sysPlat);
	
	/**
	 * 根据id查询SysPlat
	 * 
	 */
	public SysPlat  findById(Long platId);

   	
	/**
	 * 查询公司的所有平台
	 * @param company
	 * @return
	 */
	public List<SysPlat> findByCompany(SysCompany company);
	

  
}