package com.zkingsoft.services.sys;

import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysRolePwoerFn;
import java.util.List;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
public interface SysRolePwoerFnService  extends BaseServices<SysRolePwoerFn>{
	
	/**
	 * 新增SysRolePwoerFn
	 * 
	 */
	public int add(SysRolePwoerFn sysRolePwoerFn);
   	
   	/**
	 * 批量新增SysRolePwoerFn
	 * 
	 */
	public int batchAdd(List<SysRolePwoerFn>  sysRolePwoerFnList);
   	
   	/**
	 * 根据map键值对 更新SysRolePwoerFn
	 * 
	 */
	public int modifyByMap(SysRolePwoerFn oldSysRolePwoerFn ,SysRolePwoerFn newSysRolePwoerFn);
	
	/**
	 * 根据对象 更新SysRolePwoerFn
	 * 
	 */
	public int modifyByModel(SysRolePwoerFn sysRolePwoerFn);
	
	/**
	 * 批量删除SysRolePwoerFn
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除SysRolePwoerFn
	 * 
	 */
	public int removeById(Long rpfId);
	
	/**
	 * 根据对象删除SysRolePwoerFn
	 * 
	 */
	public int removeByModel(SysRolePwoerFn sysRolePwoerFn);
	
	/**
	 * 分页查询SysRolePwoerFn
	 * 
	 */
	public List<SysRolePwoerFn> findInPage(SysRolePwoerFn sysRolePwoerFn, PaginationVO pageVo);

	/**
	 * 根据对象查询SysRolePwoerFn
	 * 
	 */
	public List<SysRolePwoerFn> findByModel(SysRolePwoerFn sysRolePwoerFn);
	
	/**
	 * 统计记录数SysRolePwoerFn
	 * 
	 */
	public int  findTotal(SysRolePwoerFn sysRolePwoerFn);
	
	/**
	 * 根据id查询SysRolePwoerFn
	 * 
	 */
	public SysRolePwoerFn  findById(Long rpfId);

   	

  
}