package com.zkingsoft.services.sys;

import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysUsers;
import java.util.List;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
public interface SysUsersService  extends BaseServices<SysUsers>{
	
	/**
	 * 新增SysUsers
	 * 
	 */
	public int add(SysUsers sysUsers);
   	
   	/**
	 * 批量新增SysUsers
	 * 
	 */
	public int batchAdd(List<SysUsers>  sysUsersList);
   	
   	/**
	 * 根据map键值对 更新SysUsers
	 * 
	 */
	public int modifyByMap(SysUsers oldSysUsers ,SysUsers newSysUsers);
	
	/**
	 * 根据对象 更新SysUsers
	 * 
	 */
	public int modifyByModel(SysUsers sysUsers);
	
	/**
	 * 批量删除SysUsers
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除SysUsers
	 * 
	 */
	public int removeById(Long suId);
	
	/**
	 * 根据对象删除SysUsers
	 * 
	 */
	public int removeByModel(SysUsers sysUsers);
	
	/**
	 * 分页查询SysUsers
	 * 
	 */
	public List<SysUsers> findInPage(SysUsers sysUsers, PaginationVO pageVo);

	/**
	 * 根据对象查询SysUsers
	 * 
	 */
	public List<SysUsers> findByModel(SysUsers sysUsers);
	
	/**
	 * 统计记录数SysUsers
	 * 
	 */
	public int  findTotal(SysUsers sysUsers);
	
	/**
	 * 根据id查询SysUsers
	 * 
	 */
	public SysUsers  findById(Long suId);

	public boolean isOnlyPhone(String phone);

   	

  
}