package com.zkingsoft.syslog;

import java.util.Date;
import java.io.Serializable;
import com.zkingsoft.anotations.Extend;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-27 13:42
 */
public class SysLog implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  logId;
			
	
	/**
	 * 用户id
	 */
	private Long  userId;
			
	
	/**
	 * 创建日期
	 */
	private Date  logCreatedate;
			
	
	/**
	 * 日志内容
	 */
	private String  logContent;
			
	
	/**
	 * 用户所做的操作
	 */
	private String  logOperation;
			
	
	/**
	 * 用户名称
	 */
	private String  logUserName;
			
	
	/**
	 * 使用ip
	 */
	private String  logIp;
			
	

	public Long getLogId() {
		return logId;
	}
   	
   	public void setLogId(Long logId) {
		this.logId=logId;
	}
   	

	public Long getUserId() {
		return userId;
	}
   	
   	public void setUserId(Long userId) {
		this.userId=userId;
	}
   	

	public Date getLogCreatedate() {
		return logCreatedate;
	}
   	
   	public void setLogCreatedate(Date logCreatedate) {
		this.logCreatedate=logCreatedate;
	}
   	

	public String getLogContent() {
		return logContent;
	}
   	
   	public void setLogContent(String logContent) {
		this.logContent=logContent;
	}
   	

	public String getLogOperation() {
		return logOperation;
	}
   	
   	public void setLogOperation(String logOperation) {
		this.logOperation=logOperation;
	}
   	

	public String getLogUserName() {
		return logUserName;
	}
   	
   	public void setLogUserName(String logUserName) {
		this.logUserName=logUserName;
	}
   	

	public String getLogIp() {
		return logIp;
	}
   	
   	public void setLogIp(String logIp) {
		this.logIp=logIp;
	}
   	

	@Override
	public String toString() {
		return "{SysLog:{"
		+"logId:"+logId+","
		+"userId:"+userId+","
		+"logCreatedate:"+logCreatedate+","
		+"logContent:"+logContent+","
		+"logOperation:"+logOperation+","
		+"logUserName:"+logUserName+","
		+"logIp:"+logIp+","
		+"}}";
	}


  
}