package com.zkingsoft.syslog;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zkingsoft.pojo.PaginationVO;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-07-17 10:50
 */


public interface SysLogDao{

	public int insert(SysLog sysLog);
   	
	public int update(SysLog sysLog);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long id);
	
	public List<SysLog> selectInPage(@Param("record") SysLog sysLog, @Param("pageVo") PaginationVO pageVo);

	public List<SysLog> selectByModel(@Param("record") SysLog sysLog);
	
	public int  selectTotalRecord(@Param("record") SysLog sysLog);
	
	public SysLog  selectById(Long id);
	
}