package com.zkingsoft.actions.admin.bus;

import javax.annotation.Resource;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.zkingsoft.anotations.RemoveRequestToken;
import com.zkingsoft.anotations.SaveRequestToken;
import com.zkingsoft.authority.Authority;
import com.zkingsoft.constraint.BaseController;
import com.zkingsoft.model.bus.BusParameterSettings;
import com.zkingsoft.pojo.AjaxResult;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.services.bus.BusParameterSettingsService;
import com.zkingsoft.util.WebUtil;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-28 15:14
 */
@Controller
@RequestMapping(value = "admin/busParameterSettings")
public class BusParameterSettingsController extends BaseController{

	@Resource(name="busParameterSettingsService")
	private BusParameterSettingsService busParameterSettingsService;
	
	@Resource(name="authorityAdapter")
	private Authority  authorityAdapter;
	
	
	
	//记录编辑前的值Before_Edit_Value
	public static final String BEV="BusParameterSettings_BEV";
	
	public static final String fnCode = "BusParameterSettings";
	public static final String search = fnCode + ":search";
	public static final String edit = fnCode + ":edit";
	public static final String del = fnCode + ":del";
	public static final String add = fnCode + ":add";
	
	/**
	 * 列表显示
	 */
	@RequestMapping(value = "/showList")
	public @ResponseBody AjaxResult showList(BusParameterSettings busParameterSettings, PaginationVO pageVo) {
		authorityAdapter.isBtnPermitted(search);
		return showList(busParameterSettingsService, busParameterSettings, pageVo);
	}
   	
	/**
	 * 新增或者修改页面
	 */   
	@RemoveRequestToken	
   	@RequestMapping(value = "/addOrModify")
	public @ResponseBody AjaxResult addOrModify(BusParameterSettings busParameterSettings) {
		if (busParameterSettings.getParamId() != null) {
	   		authorityAdapter.isBtnPermitted(edit);
	   		busParameterSettings.setParamId(((BusParameterSettings)WebUtil.getSessionAttribute(BEV)).getParamId());
	   		AjaxResult result=modify(busParameterSettingsService, WebUtil.getSessionAttribute(BEV), busParameterSettings, "busParameterSettings");
			WebUtil.removeSessionAttribute(BEV);
			return  result;
		} else {
			authorityAdapter.isBtnPermitted(add);
			return add(busParameterSettingsService, busParameterSettings, "busParameterSettings");
		}
	}
	
   	/**
	 * 进入修改界面
	 */   
	@SaveRequestToken
   	@RequestMapping(value = "/editForm")
	public String editForm(Long id) {
		authorityAdapter.isBtnPermitted(edit);
		BusParameterSettings busParameterSettings;
		if (id != null) {
			busParameterSettings = busParameterSettingsService.findById(id);
			WebUtil.getRequest().setAttribute("obj", busParameterSettings);
			WebUtil.setSessionAttribute(BEV, busParameterSettings);
		}
		return "admin/busParameterSettings-form";
	}
   	
   	
   	/**
	 * 删除
	 */  
 	@RequestMapping(value = "/del")
	public @ResponseBody AjaxResult del(String keys) {
		authorityAdapter.isBtnPermitted(del);
		return remove(busParameterSettingsService, keys);
	}
  
}