package com.zkingsoft.model.sys;

import java.io.Serializable;

import com.zkingsoft.anotations.Extend;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-17 16:43
 */
public class SysBtn implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  btnId;
			
	
	private String  btnKey;
			
	
	private String  btnValue;
			
	

	public Long getBtnId() {
		return btnId;
	}
   	
   	public void setBtnId(Long btnId) {
		this.btnId=btnId;
	}
   	

	public String getBtnKey() {
		return btnKey;
	}
   	
   	public void setBtnKey(String btnKey) {
		this.btnKey=btnKey;
	}
   	

	public String getBtnValue() {
		return btnValue;
	}
   	
   	public void setBtnValue(String btnValue) {
		this.btnValue=btnValue;
	}
   	

	@Override
	public String toString() {
		return "{SysBtn:{"
		+"btnId:"+btnId+","
		+"btnKey:"+btnKey+","
		+"btnValue:"+btnValue+","
		+"}}";
	}


  
}