package com.zkingsoft.model.sys;

import com.zkingsoft.anotations.Extend;
import java.io.Serializable;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-16 18:25
 */
public class SysDbBackup implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	/**
	 * 备份表id
	 */
	private Long  buId;
			
	
	/**
	 * 数据库ip地址
	 */
	private String  buDbIp;
			
	
	/**
	 * 数据库端口号
	 */
	private String  buDbPort;
			
	
	/**
	 * 数据库名称
	 */
	private String  buDbName;
			
	
	/**
	 * 数据库用户名
	 */
	private String  buDbUname;
			
	
	/**
	 * 数据库用户密码
	 */
	private String  buDbPwd;
			
	
	/**
	 * 备份状态（0.失败 1.成功）
	 */
	private String  buStatus;
			
	
	/**
	 * 备份文件大小
	 */
	private Integer  buSize;
			
	
	/**
	 * 备份文件路径
	 */
	private String  buPath;
			
	
	/**
	 * 备份错误信息
	 */
	private String  buErrMsg;
			
	

	public Long getBuId() {
		return buId;
	}
   	
   	public void setBuId(Long buId) {
		this.buId=buId;
	}
   	

	public String getBuDbIp() {
		return buDbIp;
	}
   	
   	public void setBuDbIp(String buDbIp) {
		this.buDbIp=buDbIp;
	}
   	

	public String getBuDbPort() {
		return buDbPort;
	}
   	
   	public void setBuDbPort(String buDbPort) {
		this.buDbPort=buDbPort;
	}
   	

	public String getBuDbName() {
		return buDbName;
	}
   	
   	public void setBuDbName(String buDbName) {
		this.buDbName=buDbName;
	}
   	

	public String getBuDbUname() {
		return buDbUname;
	}
   	
   	public void setBuDbUname(String buDbUname) {
		this.buDbUname=buDbUname;
	}
   	

	public String getBuDbPwd() {
		return buDbPwd;
	}
   	
   	public void setBuDbPwd(String buDbPwd) {
		this.buDbPwd=buDbPwd;
	}
   	

	public String getBuStatus() {
		return buStatus;
	}
   	
   	public void setBuStatus(String buStatus) {
		this.buStatus=buStatus;
	}
   	

	public Integer getBuSize() {
		return buSize;
	}
   	
   	public void setBuSize(Integer buSize) {
		this.buSize=buSize;
	}
   	

	public String getBuPath() {
		return buPath;
	}
   	
   	public void setBuPath(String buPath) {
		this.buPath=buPath;
	}
   	

	public String getBuErrMsg() {
		return buErrMsg;
	}
   	
   	public void setBuErrMsg(String buErrMsg) {
		this.buErrMsg=buErrMsg;
	}
   	

	@Override
	public String toString() {
		return "{SysDbBackup:{"
		+"buId:"+buId+","
		+"buDbIp:"+buDbIp+","
		+"buDbPort:"+buDbPort+","
		+"buDbName:"+buDbName+","
		+"buDbUname:"+buDbUname+","
		+"buDbPwd:"+buDbPwd+","
		+"buStatus:"+buStatus+","
		+"buSize:"+buSize+","
		+"buPath:"+buPath+","
		+"buErrMsg:"+buErrMsg+","
		+"}}";
	}


  
}