package com.zkingsoft.model.sys;

import java.io.Serializable;
import java.util.List;

import com.zkingsoft.anotations.Extend;

/**
 * This field was generated by Zking.software.Codegen.
 * 
 * @date 2016-11-16 15:25
 */
public class SysFunction implements Serializable {

	@Extend
	private static final long serialVersionUID = 1L;

	private Long fnId;

	private String fnIcon;

	private String fnPath;

	/**
	 * 是禁用吗
	 */
	private String fnIsDisable;

	/**
	 * 功能等级
	 */
	private Integer fnGrade;

	/**
	 * 父级功能
	 */
	private Long fnParentId;

	private String fnName;

	/**
	 * 排序字段
	 */
	private Integer fnSequence;

	/**
	 * 功能code
	 */
	private String fnCode;

	/**
	 * 功能所具有的按钮
	 */
	private String fnBtns;

	/**
	 * 是在菜单栏显示吗
	 */
	private String fnShowMenu;
	/**
	 * 功能的子功能
	 */
	@Extend
	private List<SysFunction> childs;
	/**
	 * 功能对应的按钮集合
	 */
	@Extend
	private List<SysBtn> sysBtns;
	/**
	 * 在权限分配时用于标记是否拥有该项功能
	 */
	@Extend
	private boolean hasThisFn=false;
	
	

	public List<SysBtn> getSysBtns() {
		return sysBtns;
	}

	public void setSysBtns(List<SysBtn> sysBtns) {
		this.sysBtns = sysBtns;
	}

	public boolean getHasThisFn() {
		return hasThisFn;
	}

	public void setHasThisFn(boolean hasThisFn) {
		this.hasThisFn = hasThisFn;
	}

	public List<SysFunction> getChilds() {
		return childs;
	}

	public void setChilds(List<SysFunction> childs) {
		this.childs = childs;
	}

	public String getFnShowMenu() {
		return fnShowMenu;
	}

	public void setFnShowMenu(String fnShowMenu) {
		this.fnShowMenu = fnShowMenu;
	}

	public Long getFnId() {
		return fnId;
	}

	public void setFnId(Long fnId) {
		this.fnId = fnId;
	}

	public String getFnIcon() {
		return fnIcon;
	}

	public void setFnIcon(String fnIcon) {
		this.fnIcon = fnIcon;
	}

	public String getFnPath() {
		return fnPath;
	}

	public void setFnPath(String fnPath) {
		this.fnPath = fnPath;
	}

	public String getFnIsDisable() {
		return fnIsDisable;
	}

	public void setFnIsDisable(String fnIsDisable) {
		this.fnIsDisable = fnIsDisable;
	}

	public Integer getFnGrade() {
		return fnGrade;
	}

	public void setFnGrade(Integer fnGrade) {
		this.fnGrade = fnGrade;
	}

	public Long getFnParentId() {
		return fnParentId;
	}

	public void setFnParentId(Long fnParentId) {
		this.fnParentId = fnParentId;
	}

	public String getFnName() {
		return fnName;
	}

	public void setFnName(String fnName) {
		this.fnName = fnName;
	}

	public Integer getFnSequence() {
		return fnSequence;
	}

	public void setFnSequence(Integer fnSequence) {
		this.fnSequence = fnSequence;
	}

	public String getFnCode() {
		return fnCode;
	}

	public void setFnCode(String fnCode) {
		this.fnCode = fnCode;
	}

	public String getFnBtns() {
		return fnBtns;
	}

	public void setFnBtns(String fnBtns) {
		this.fnBtns = fnBtns;
	}

	@Override
	public String toString() {
		return "{SysFunction:{" + "fnId:" + fnId + "," + "fnIcon:" + fnIcon + "," + "fnPath:" + fnPath + ","
				+ "fnIsDisable:" + fnIsDisable + "," + "fnGrade:" + fnGrade + "," + "fnParentId:" + fnParentId + ","
				+ "fnName:" + fnName + "," + "fnSequence:" + fnSequence + "," + "fnCode:" + fnCode + "," + "fnBtns:"
				+ fnBtns + "," + "}}";
	}

}