package com.zkingsoft.model.sys;

import java.io.Serializable;
import java.util.List;

import com.zkingsoft.anotations.Extend;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
public class SysRole implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  roleId;
			
	
	private String  roleName;
			
	
	private String  roleRemark;
			
	
	private Long  companyId;
			
	
	/**
	 * 角色所拥有的平台
	 */
	private String  plates;
		
	/**
	 *功能集合 
	 */
	@Extend
	private List<SysFunction> fnList;
	
	
	

	public List<SysFunction> getFnList() {
		return fnList;
	}

	public void setFnList(List<SysFunction> fnList) {
		this.fnList = fnList;
	}

	public Long getRoleId() {
		return roleId;
	}
   	
   	public void setRoleId(Long roleId) {
		this.roleId=roleId;
	}
   	

	public String getRoleName() {
		return roleName;
	}
   	
   	public void setRoleName(String roleName) {
		this.roleName=roleName;
	}
   	

	public String getRoleRemark() {
		return roleRemark;
	}
   	
   	public void setRoleRemark(String roleRemark) {
		this.roleRemark=roleRemark;
	}
   	

	public Long getCompanyId() {
		return companyId;
	}
   	
   	public void setCompanyId(Long companyId) {
		this.companyId=companyId;
	}
   	

	public String getPlates() {
		return plates;
	}
   	
   	public void setPlates(String plates) {
		this.plates=plates;
	}
   	

	@Override
	public String toString() {
		return "{SysRole:{"
		+"roleId:"+roleId+","
		+"roleName:"+roleName+","
		+"roleRemark:"+roleRemark+","
		+"companyId:"+companyId+","
		+"plates:"+plates+","
		+"}}";
	}


  
}