package com.zkingsoft.model.sys;

import java.io.Serializable;

import com.zkingsoft.anotations.Extend;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
public class SysRolePwoerFn implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  rpfId;
			
	
	/**
	 * 角色id
	 */
	private Long  roleId;
			
	
	/**
	 * 功能id
	 */
	private Long  fnId;
			
	
	/**
	 * 按钮s
	 */
	private String  rpfBtns;
			
	

	public Long getRpfId() {
		return rpfId;
	}
   	
   	public void setRpfId(Long rpfId) {
		this.rpfId=rpfId;
	}
   	

	public Long getRoleId() {
		return roleId;
	}
   	
   	public void setRoleId(Long roleId) {
		this.roleId=roleId;
	}
   	

	public Long getFnId() {
		return fnId;
	}
   	
   	public void setFnId(Long fnId) {
		this.fnId=fnId;
	}
   	

	public String getRpfBtns() {
		return rpfBtns;
	}
   	
   	public void setRpfBtns(String rpfBtns) {
		this.rpfBtns=rpfBtns;
	}
   	

	@Override
	public String toString() {
		return "{SysRolePwoerFn:{"
		+"rpfId:"+rpfId+","
		+"roleId:"+roleId+","
		+"fnId:"+fnId+","
		+"rpfBtns:"+rpfBtns+","
		+"}}";
	}


  
}