package com.zkingsoft.model.sys;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.SystemUtils;

import com.zkingsoft.anotations.Extend;

/**
 * This field was generated by Zking.software.Codegen.
 * 
 * @date 2016-11-16 15:25
 */
public class SysUsers implements Serializable {
	@Extend
	private static final long serialVersionUID = 1L;

	private Long suId;

	/**
	 * 真实姓名
	 */
	private String suName;

	/**
	 * 电话号码
	 */
	private String suTel;

	/**
	 * 住址
	 */
	private String suAddress;

	/**
	 * 头像
	 */
	private String suPhoto;

	/**
	 * 性别
	 */
	private String suSex;

	/**
	 * 角色
	 */
	private Long roleId;

	/**
	 * 邮箱
	 */
	private String suEmail;

	/**
	 * 账号
	 */
	private String suAccount;

	/**
	 * 密码
	 */
	private String suPassword;

	/**
	 * 注册时间
	 */
	private Date suRegisterTime;

	/**
	 * qqid
	 */
	private String suQqId;

	/**
	 * 微信id
	 */
	private String suWeixinId;

	/**
	 * 等级
	 */
	private String suGrade;

	/**
	 * 推荐人
	 */
	private Long parentUserId;

	/**
	 * 部门
	 */
	private Long suDeptId;

	/**
	 * 用户类型
	 */
	private String suUserType;

	/**
	 * 微博id
	 */
	private String suWeiboId;

	/**
	 * 身份证
	 */
	private String suIdcard;

	/**
	 * 职称
	 */
	private String suJobTitle;

	/**
	 * 别名，昵称
	 */
	private String suAliases;

	/**
	 * 工作编号
	 */
	private String suJobNo;

	/**
	 * 公司id
	 */
	private Long companyId;

	/**
	 * 备用电话号码
	 */
	private String suTel2;

	/**
	 * 账户状态
	 */
	private String suAccountStatus;

	/**
	 * 激活码
	 */
	private String suValidateCode;

	/**
	 * 激活最后时间
	 */
	private Date suValidateEndTime;

	/**
	 * Y 有效，N无效
	 */
	private String suValid;

	/**
	 * 生日
	 */
	private Date suBirthday;

	/**
	 * 用户uuid
	 */
	private String suUuid;

	/**
	 * 岗位id
	 */
	private Long suPostId;
	/**
	 * 用户对于的角色集合
	 */
	private String roleIds;

	public String getRoleIds() {
		return roleIds;
	}

	public void setRoleIds(String roleIds) {
		this.roleIds = roleIds;
	}

	@Extend
	private String companyName;

	@Extend
	private SysCompany company;

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public SysCompany getCompany() {
		return company;
	}

	public void setCompany(SysCompany company) {
		this.company = company;
	}

	public Long getSuId() {
		return suId;
	}

	public void setSuId(Long suId) {
		this.suId = suId;
	}

	public String getSuName() {
		return suName;
	}

	public void setSuName(String suName) {
		this.suName = suName;
	}

	public String getSuTel() {
		return suTel;
	}

	public void setSuTel(String suTel) {
		this.suTel = suTel;
	}

	public String getSuAddress() {
		return suAddress;
	}

	public void setSuAddress(String suAddress) {
		this.suAddress = suAddress;
	}

	public String getSuPhoto() {
		return suPhoto;
	}

	public void setSuPhoto(String suPhoto) {
		this.suPhoto = suPhoto;
	}

	public String getSuSex() {
		return suSex;
	}

	public void setSuSex(String suSex) {
		this.suSex = suSex;
	}

	public Long getRoleId() {
		return roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getSuEmail() {
		return suEmail;
	}

	public void setSuEmail(String suEmail) {
		this.suEmail = suEmail;
	}

	public String getSuAccount() {
		return suAccount;
	}

	public void setSuAccount(String suAccount) {
		this.suAccount = suAccount;
	}

	public String getSuPassword() {
		return suPassword;
	}

	public void setSuPassword(String suPassword) {
		this.suPassword = suPassword;
	}

	public Date getSuRegisterTime() {
		return suRegisterTime;
	}

	public void setSuRegisterTime(Date suRegisterTime) {
		this.suRegisterTime = suRegisterTime;
	}

	public String getSuQqId() {
		return suQqId;
	}

	public void setSuQqId(String suQqId) {
		this.suQqId = suQqId;
	}

	public String getSuWeixinId() {
		return suWeixinId;
	}

	public void setSuWeixinId(String suWeixinId) {
		this.suWeixinId = suWeixinId;
	}

	public String getSuGrade() {
		return suGrade;
	}

	public void setSuGrade(String suGrade) {
		this.suGrade = suGrade;
	}

	public Long getParentUserId() {
		return parentUserId;
	}

	public void setParentUserId(Long parentUserId) {
		this.parentUserId = parentUserId;
	}

	public Long getSuDeptId() {
		return suDeptId;
	}

	public void setSuDeptId(Long suDeptId) {
		this.suDeptId = suDeptId;
	}

	public String getSuUserType() {
		return suUserType;
	}

	public void setSuUserType(String suUserType) {
		this.suUserType = suUserType;
	}

	public String getSuWeiboId() {
		return suWeiboId;
	}

	public void setSuWeiboId(String suWeiboId) {
		this.suWeiboId = suWeiboId;
	}

	public String getSuIdcard() {
		return suIdcard;
	}

	public void setSuIdcard(String suIdcard) {
		this.suIdcard = suIdcard;
	}

	public String getSuJobTitle() {
		return suJobTitle;
	}

	public void setSuJobTitle(String suJobTitle) {
		this.suJobTitle = suJobTitle;
	}

	public String getSuAliases() {
		return suAliases;
	}

	public void setSuAliases(String suAliases) {
		this.suAliases = suAliases;
	}

	public String getSuJobNo() {
		return suJobNo;
	}

	public void setSuJobNo(String suJobNo) {
		this.suJobNo = suJobNo;
	}

	public Long getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	public String getSuTel2() {
		return suTel2;
	}

	public void setSuTel2(String suTel2) {
		this.suTel2 = suTel2;
	}

	public String getSuAccountStatus() {
		return suAccountStatus;
	}

	public void setSuAccountStatus(String suAccountStatus) {
		this.suAccountStatus = suAccountStatus;
	}

	public String getSuValidateCode() {
		return suValidateCode;
	}

	public void setSuValidateCode(String suValidateCode) {
		this.suValidateCode = suValidateCode;
	}

	public Date getSuValidateEndTime() {
		return suValidateEndTime;
	}

	public void setSuValidateEndTime(Date suValidateEndTime) {
		this.suValidateEndTime = suValidateEndTime;
	}

	public String getSuValid() {
		return suValid;
	}

	public void setSuValid(String suValid) {
		this.suValid = suValid;
	}

	public Date getSuBirthday() {
		return suBirthday;
	}

	public void setSuBirthday(Date suBirthday) {
		this.suBirthday = suBirthday;
	}

	public String getSuUuid() {
		return suUuid;
	}

	public void setSuUuid(String suUuid) {
		this.suUuid = suUuid;
	}

	public Long getSuPostId() {
		return suPostId;
	}

	public void setSuPostId(Long suPostId) {
		this.suPostId = suPostId;
	}

	@Override
	public String toString() {
		return "{SysUsers:{" + "suId:" + suId + "," + "suName:" + suName + "," + "suTel:" + suTel + "," + "suAddress:"
				+ suAddress + "," + "suPhoto:" + suPhoto + "," + "suSex:" + suSex + "," + "roleId:" + roleId + ","
				+ "suEmail:" + suEmail + "," + "suAccount:" + suAccount + "," + "suPassword:" + suPassword + ","
				+ "suRegisterTime:" + suRegisterTime + "," + "suQqId:" + suQqId + "," + "suWeixinId:" + suWeixinId + ","
				+ "suGrade:" + suGrade + "," + "parentUserId:" + parentUserId + "," + "suDeptId:" + suDeptId + ","
				+ "suUserType:" + suUserType + "," + "suWeiboId:" + suWeiboId + "," + "suIdcard:" + suIdcard + ","
				+ "suJobTitle:" + suJobTitle + "," + "suAliases:" + suAliases + "," + "suJobNo:" + suJobNo + ","
				+ "companyId:" + companyId + "," + "suTel2:" + suTel2 + "," + "suAccountStatus:" + suAccountStatus + ","
				+ "suValidateCode:" + suValidateCode + "," + "suValidateEndTime:" + suValidateEndTime + "," + "suValid:"
				+ suValid + "," + "suBirthday:" + suBirthday + "," + "suUuid:" + suUuid + "," + "suPostId:" + suPostId
				+ "," + "}}";
	}
}
