package com.zkingsoft.model.bus;

import com.zkingsoft.anotations.Extend;
import java.io.Serializable;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-28 16:55
 */
public class BusCatalog implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  cataId;
			
	
	/**
	 * 分类名称
	 */
	private String  cataName;
			
	
	/**
	 * 分类的类型
	 */
	private String  cataType;
			
	
	/**
	 * 分类的图标
	 */
	private String  cataIcon;
			
	
	/**
	 * 所属公司id
	 */
	private Long  cataCompanyId;
			
	
	/**
	 * 父级分类
	 */
	private Long  parentId;
			
	
	/**
	 * 预留字段
	 */
	private String  cataInfo1;
			
	
	private String  cataInfo2;
			
	
	private String  cataInfo3;
			
	
	private String  cataInfo4;
			
	
	/**
	 * 排序字段
	 */
	private Long  cataSequnce;
			
	
	/**
	 * 扩展字段
	 */
	private String parentName;
	
	
	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public Long getCataId() {
		return cataId;
	}
   	
   	public void setCataId(Long cataId) {
		this.cataId=cataId;
	}
   	

	public String getCataName() {
		return cataName;
	}
   	
   	public void setCataName(String cataName) {
		this.cataName=cataName;
	}
   	

	public String getCataType() {
		return cataType;
	}
   	
   	public void setCataType(String cataType) {
		this.cataType=cataType;
	}
   	

	public String getCataIcon() {
		return cataIcon;
	}
   	
   	public void setCataIcon(String cataIcon) {
		this.cataIcon=cataIcon;
	}
   	

	public Long getCataCompanyId() {
		return cataCompanyId;
	}
   	
   	public void setCataCompanyId(Long cataCompanyId) {
		this.cataCompanyId=cataCompanyId;
	}
   	

	public Long getParentId() {
		return parentId;
	}
   	
   	public void setParentId(Long parentId) {
		this.parentId=parentId;
	}
   	

	public String getCataInfo1() {
		return cataInfo1;
	}
   	
   	public void setCataInfo1(String cataInfo1) {
		this.cataInfo1=cataInfo1;
	}
   	

	public String getCataInfo2() {
		return cataInfo2;
	}
   	
   	public void setCataInfo2(String cataInfo2) {
		this.cataInfo2=cataInfo2;
	}
   	

	public String getCataInfo3() {
		return cataInfo3;
	}
   	
   	public void setCataInfo3(String cataInfo3) {
		this.cataInfo3=cataInfo3;
	}
   	

	public String getCataInfo4() {
		return cataInfo4;
	}
   	
   	public void setCataInfo4(String cataInfo4) {
		this.cataInfo4=cataInfo4;
	}
   	

	public Long getCataSequnce() {
		return cataSequnce;
	}
   	
   	public void setCataSequnce(Long cataSequnce) {
		this.cataSequnce=cataSequnce;
	}
   	

	@Override
	public String toString() {
		return "{BusCatalog:{"
		+"cataId:"+cataId+","
		+"cataName:"+cataName+","
		+"cataType:"+cataType+","
		+"cataIcon:"+cataIcon+","
		+"cataCompanyId:"+cataCompanyId+","
		+"parentId:"+parentId+","
		+"cataInfo1:"+cataInfo1+","
		+"cataInfo2:"+cataInfo2+","
		+"cataInfo3:"+cataInfo3+","
		+"cataInfo4:"+cataInfo4+","
		+"cataSequnce:"+cataSequnce+","
		+"}}";
	} 


  
}