package com.zkingsoft.model.bus;

import com.zkingsoft.anotations.Extend;
import java.io.Serializable;
/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-28 16:55
 */
public class BusParameterSettings implements Serializable{
	@Extend
	private static final long serialVersionUID = 1L; 

	
	private Long  paramId;
			
	
	/**
	 * 参数编码
	 */
	private String  paramCode;
			
	
	/**
	 * 参数值
	 */
	private String  paramValue;
			
	
	/**
	 * 值1
	 */
	private String  paramValue1;
			
	
	/**
	 * 值2
	 */
	private String  paramValue2;
			
	
	/**
	 * 值3
	 */
	private String  paramValue3;
			
	

	public Long getParamId() {
		return paramId;
	}
   	
   	public void setParamId(Long paramId) {
		this.paramId=paramId;
	}
   	

	public String getParamCode() {
		return paramCode;
	}
   	
   	public void setParamCode(String paramCode) {
		this.paramCode=paramCode;
	}
   	

	public String getParamValue() {
		return paramValue;
	}
   	
   	public void setParamValue(String paramValue) {
		this.paramValue=paramValue;
	}
   	

	public String getParamValue1() {
		return paramValue1;
	}
   	
   	public void setParamValue1(String paramValue1) {
		this.paramValue1=paramValue1;
	}
   	

	public String getParamValue2() {
		return paramValue2;
	}
   	
   	public void setParamValue2(String paramValue2) {
		this.paramValue2=paramValue2;
	}
   	

	public String getParamValue3() {
		return paramValue3;
	}
   	
   	public void setParamValue3(String paramValue3) {
		this.paramValue3=paramValue3;
	}
   	

	@Override
	public String toString() {
		return "{BusParameterSettings:{"
		+"paramId:"+paramId+","
		+"paramCode:"+paramCode+","
		+"paramValue:"+paramValue+","
		+"paramValue1:"+paramValue1+","
		+"paramValue2:"+paramValue2+","
		+"paramValue3:"+paramValue3+","
		+"}}";
	}

 
  
}