package com.zkingsoft.dao.bus;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import java.util.List;
import com.zkingsoft.model.bus.BusCatalog;
import java.util.Map;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-28 16:55
 */


public interface BusCatalogDao{

	public int insert(BusCatalog busCatalog);
   	
   	public int batchInsert(@Param("list") List<BusCatalog> busCatalogList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(BusCatalog busCatalog);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long cataId);

	public int deleteByModel(@Param("record") BusCatalog busCatalog);
	
	public List<BusCatalog> selectInPage(@Param("record") BusCatalog busCatalog, @Param("pageVo") PaginationVO pageVo);

	public List<BusCatalog> selectByModel(@Param("record") BusCatalog busCatalog);
	
	public int  selectTotalRecord(@Param("record") BusCatalog busCatalog);
	
	public BusCatalog  selectById(Long cataId);
	
	public BusCatalog  selectForUpdate(Long cataId);
	
} 