package com.zkingsoft.dao.bus;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import java.util.List;
import com.zkingsoft.model.bus.BusParameterSettings;
import java.util.Map;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-28 16:55
 */
 

public interface BusParameterSettingsDao{

	public int insert(BusParameterSettings busParameterSettings);
   	
   	public int batchInsert(@Param("list") List<BusParameterSettings> busParameterSettingsList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(BusParameterSettings busParameterSettings);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long paramId);

	public int deleteByModel(@Param("record") BusParameterSettings busParameterSettings);
	
	public List<BusParameterSettings> selectInPage(@Param("record") BusParameterSettings busParameterSettings, @Param("pageVo") PaginationVO pageVo);

	public List<BusParameterSettings> selectByModel(@Param("record") BusParameterSettings busParameterSettings);
	
	public int  selectTotalRecord(@Param("record") BusParameterSettings busParameterSettings);
	
	public BusParameterSettings  selectById(Long paramId);
	
	public BusParameterSettings  selectForUpdate(Long paramId);
	
}