package com.zkingsoft.actions.admin.sys;

import javax.annotation.Resource;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.zkingsoft.anotations.RemoveRequestToken;
import com.zkingsoft.anotations.SaveRequestToken;
import com.zkingsoft.authority.Authority;
import com.zkingsoft.constraint.BaseController;
import com.zkingsoft.model.sys.SysCompany;
import com.zkingsoft.pojo.AjaxResult;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.services.sys.SysCompanyService;
import com.zkingsoft.util.WebUtil;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */
@Controller
@RequestMapping(value = "admin/sysCompany")
public class SysCompanyController extends BaseController{

	@Resource(name="sysCompanyService")
	private SysCompanyService sysCompanyService;
	
	@Resource(name="authorityAdapter")
	private Authority  authorityAdapter;
	
	//记录编辑前的值Before_Edit_Value
	public static final String BEV="SysCompany_BEV";
	public static final String fnCode = "company";
	public static final String search = fnCode + ":search";
	public static final String edit = fnCode + ":edit";
	public static final String del = fnCode + ":del";
	public static final String add = fnCode + ":add";
	
	/**
	 * 列表显示
	 */
	@RequestMapping(value = "/showList")
	public @ResponseBody AjaxResult showList(SysCompany sysCompany, PaginationVO pageVo) {
		authorityAdapter.isBtnPermitted(search);
		return showList(sysCompanyService, sysCompany, pageVo);
	}
	
	/**
	 * 显示所有
	 */
	@RequestMapping(value = "/all")
	public @ResponseBody AjaxResult all() {
		return new AjaxResult(AjaxResult.STATUS_OK,sysCompanyService.findByModel(null));
	}
   	
	/**
	 * 新增或者修改页面
	 */   
	@RemoveRequestToken	
   	@RequestMapping(value = "/addOrModify")
	public @ResponseBody AjaxResult addOrModify(SysCompany sysCompany) {
		if (sysCompany.getComId() != null) {
			authorityAdapter.isBtnPermitted(edit);
			sysCompany.setComId(((SysCompany)( WebUtil.getSessionAttribute(BEV))).getComId());
	   		AjaxResult result=modify(sysCompanyService, WebUtil.getSessionAttribute(BEV), sysCompany,"公司");
			WebUtil.removeSessionAttribute(BEV);
			return  result;
		} else {
			authorityAdapter.isBtnPermitted(add);
			return add(sysCompanyService, sysCompany, "公司");
		}
	}
	
   	/**
	 * 进入修改界面
	 */   
	@SaveRequestToken
   	@RequestMapping(value = "/editForm")
	public String editForm(Long id) {
		authorityAdapter.isBtnPermitted(edit);
		SysCompany sysCompany;
		if (id != null) {
			sysCompany = sysCompanyService.findById(id);
			WebUtil.getRequest().setAttribute("obj", sysCompany);
			WebUtil.setSessionAttribute(BEV, sysCompany);
		}
		return "super/sysCompany-form";
	}
   	
   	
   	/**
	 * 删除
	 */  
 	@RequestMapping(value = "/del")
	public @ResponseBody AjaxResult del(String keys) {
 		authorityAdapter.isBtnPermitted(del);
		return remove(sysCompanyService, keys);
	}
  
}