package com.zkingsoft.services.web;

import com.zkingsoft.pojo.PaginationVO;
import java.util.List;
import com.zkingsoft.model.web.WebArticleType;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-01 10:36
 */
public interface WebArticleTypeService  extends BaseServices<WebArticleType>{
	
	/**
	 * 新增WebArticleType
	 * 
	 */
	public int add(WebArticleType webArticleType);
   	
   	/**
	 * 批量新增WebArticleType
	 * 
	 */
	public int batchAdd(List<WebArticleType>  webArticleTypeList);
   	
   	/**
	 * 根据map键值对 更新WebArticleType
	 * 
	 */
	public int modifyByMap(WebArticleType oldWebArticleType ,WebArticleType newWebArticleType);
	
	/**
	 * 根据对象 更新WebArticleType
	 * 
	 */
	public int modifyByModel(WebArticleType webArticleType);
	
	/**
	 * 批量删除WebArticleType
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除WebArticleType
	 * 
	 */
	public int removeById(Long artTypeId);
	
	/**
	 * 根据对象删除WebArticleType
	 * 
	 */
	public int removeByModel(WebArticleType webArticleType);
	
	/**
	 * 分页查询WebArticleType
	 * 
	 */
	public List<WebArticleType> findInPage(WebArticleType webArticleType, PaginationVO pageVo);

	/**
	 * 根据对象查询WebArticleType
	 * 
	 */
	public List<WebArticleType> findByModel(WebArticleType webArticleType);
	
	/**
	 * 统计记录数WebArticleType
	 * 
	 */
	public int  findTotal(WebArticleType webArticleType);
	
	/**
	 * 根据id查询WebArticleType
	 * 
	 */
	public WebArticleType  findById(Long artTypeId);

   	

  
}