package com.zkingsoft.dao.sys;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysBtn;
import java.util.Map;
import java.util.List;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */


public interface SysBtnDao{

	/** 插入方法 */
	public int insert(SysBtn sysBtn);
	/** 批量插入方法 */
   	public int batchInsert(@Param("list") List<SysBtn> sysBtnList);
   	/** 根据map键值对更新 */
	public int updateByMap(Map<String, Object> modifyMap);
	/** 根据对象模型更新 */
	public int updateByModel(SysBtn sysBtn);
	/** 批量删除 */
	public int deleteByIds(@Param("list") List<Long> list);
	/** 根据id删除 */
	public int deleteById(Long id);
	/** 根据对象进行条件删除 */
	public int deleteByModel(@Param("record") SysBtn sysBtn);
	/** 分页查询 */
	public List<SysBtn> selectInPage(@Param("record") SysBtn sysBtn, @Param("pageVo") PaginationVO pageVo);
	/** 根据对象查询不分页 */
	public List<SysBtn> selectByModel(@Param("record") SysBtn sysBtn);
	/** 查询总条数 */
	public int  selectTotalRecord(@Param("record") SysBtn sysBtn);
	/** 根据id查询 */
	public SysBtn  selectById(Long id);
	/** 锁表查询 */
	public SysBtn  selectForUpdate(Long id);
	
}