package com.zkingsoft.dao.sys;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysCompany;
import java.util.Map;
import java.util.List;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */


public interface SysCompanyDao{

	public int insert(SysCompany sysCompany);
   	
   	public int batchInsert(@Param("list") List<SysCompany> sysCompanyList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(SysCompany sysCompany);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long comId);

	public int deleteByModel(@Param("record") SysCompany sysCompany);
	
	public List<SysCompany> selectInPage(@Param("record") SysCompany sysCompany, @Param("pageVo") PaginationVO pageVo);

	public List<SysCompany> selectByModel(@Param("record") SysCompany sysCompany);
	
	public int  selectTotalRecord(@Param("record") SysCompany sysCompany);
	
	public SysCompany  selectById(Long comId);
	
	public SysCompany  selectForUpdate(Long comId);
	
}