package com.zkingsoft.dao.sys;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysDataDictionary;
import java.util.Map;
import java.util.List;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */


public interface SysDataDictionaryDao{

	public int insert(SysDataDictionary sysDataDictionary);
   	
   	public int batchInsert(@Param("list") List<SysDataDictionary> sysDataDictionaryList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(SysDataDictionary sysDataDictionary);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long dicId);

	public int deleteByModel(@Param("record") SysDataDictionary sysDataDictionary);
	
	public List<SysDataDictionary> selectInPage(@Param("record") SysDataDictionary sysDataDictionary, @Param("pageVo") PaginationVO pageVo);

	public List<SysDataDictionary> selectByModel(@Param("record") SysDataDictionary sysDataDictionary);
	
	public int  selectTotalRecord(@Param("record") SysDataDictionary sysDataDictionary);
	
	public SysDataDictionary  selectById(Long dicId);
	
	public SysDataDictionary  selectForUpdate(Long dicId);
	
}