package com.zkingsoft.dao.sys;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysDbBackup;
import java.util.Map;
import java.util.List;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-16 18:25
 */


public interface SysDbBackupDao{

	public int insert(SysDbBackup sysDbBackup);
   	
   	public int batchInsert(@Param("list") List<SysDbBackup> sysDbBackupList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(SysDbBackup sysDbBackup);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long buId);

	public int deleteByModel(@Param("record") SysDbBackup sysDbBackup);
	
	public List<SysDbBackup> selectInPage(@Param("record") SysDbBackup sysDbBackup, @Param("pageVo") PaginationVO pageVo);

	public List<SysDbBackup> selectByModel(@Param("record") SysDbBackup sysDbBackup);
	
	public int  selectTotalRecord(@Param("record") SysDbBackup sysDbBackup);
	
	public SysDbBackup  selectById(Long buId);
	
	public SysDbBackup  selectForUpdate(Long buId);
	
}