package com.zkingsoft.dao.sys;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysFunction;
import java.util.Map;
import java.util.List;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */


public interface SysFunctionDao{

	public int insert(SysFunction sysFunction);
   	
   	public int batchInsert(@Param("list") List<SysFunction> sysFunctionList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(SysFunction sysFunction);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long fnId);

	public int deleteByModel(@Param("record") SysFunction sysFunction);
	
	public List<SysFunction> selectInPage(@Param("record") SysFunction sysFunction, @Param("pageVo") PaginationVO pageVo);

	public List<SysFunction> selectByModel(@Param("record") SysFunction sysFunction);
	
	public int  selectTotalRecord(@Param("record") SysFunction sysFunction);
	
	public SysFunction  selectById(Long fnId);
	
	public SysFunction  selectForUpdate(Long fnId);
	
	/**
	 * 根据公司id查询功能
	 * @param companyId
	 * @return
	 */
	public List<SysFunction> selectCompanyFunction(Long companyId);

	public List<SysFunction> selectFunctionByRoleIds(String roleIds);

	public void batchChangeStatu(@Param("status") String status,@Param("list")  List<Long> list);
	
}