package com.zkingsoft.dao.sys;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysCompany;
import com.zkingsoft.model.sys.SysPlat;
import java.util.Map;
import java.util.List;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */


public interface SysPlatDao{

	public int insert(SysPlat sysPlat);
   	
   	public int batchInsert(@Param("list") List<SysPlat> sysPlatList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(SysPlat sysPlat);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long platId);

	public int deleteByModel(@Param("record") SysPlat sysPlat);
	
	public List<SysPlat> selectInPage(@Param("record") SysPlat sysPlat, @Param("pageVo") PaginationVO pageVo);

	public List<SysPlat> selectByModel(@Param("record") SysPlat sysPlat);
	
	public int  selectTotalRecord(@Param("record") SysPlat sysPlat);
	
	public SysPlat  selectById(Long platId);
	
	public SysPlat  selectForUpdate(Long platId);
	
	public List<SysPlat> selectByCompany(@Param("company") SysCompany company);
	
}