package com.zkingsoft.dao.sys;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysRole;
import java.util.Map;
import java.util.List;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */


public interface SysRoleDao{

	public int insert(SysRole sysRole);
   	
   	public int batchInsert(@Param("list") List<SysRole> sysRoleList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(SysRole sysRole);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long roleId);

	public int deleteByModel(@Param("record") SysRole sysRole);
	
	public List<SysRole> selectInPage(@Param("record") SysRole sysRole, @Param("pageVo") PaginationVO pageVo);

	public List<SysRole> selectByModel(@Param("record") SysRole sysRole);
	
	public int  selectTotalRecord(@Param("record") SysRole sysRole);
	
	public SysRole  selectById(Long roleId);
	
	public SysRole  selectForUpdate(Long roleId);
	
}