package com.zkingsoft.dao.sys;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.model.sys.SysRolePwoerFn;
import java.util.Map;
import java.util.List;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-16 15:25
 */


public interface SysRolePwoerFnDao{

	public int insert(SysRolePwoerFn sysRolePwoerFn);
   	
   	public int batchInsert(@Param("list") List<SysRolePwoerFn> sysRolePwoerFnList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(SysRolePwoerFn sysRolePwoerFn);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long rpfId);

	public int deleteByModel(@Param("record") SysRolePwoerFn sysRolePwoerFn);
	
	public List<SysRolePwoerFn> selectInPage(@Param("record") SysRolePwoerFn sysRolePwoerFn, @Param("pageVo") PaginationVO pageVo);

	public List<SysRolePwoerFn> selectByModel(@Param("record") SysRolePwoerFn sysRolePwoerFn);
	
	public int  selectTotalRecord(@Param("record") SysRolePwoerFn sysRolePwoerFn);
	
	public SysRolePwoerFn  selectById(Long rpfId);
	
	public SysRolePwoerFn  selectForUpdate(Long rpfId);
	
}