package com.zkingsoft.dao.sys;

import java.util.HashMap;

import org.apache.ibatis.annotations.Param;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-04-22 08:43
 */


public interface UtilDao{
	/**
	 * 如果返回多条记录则会报错
	 * 单字段去重
	 * @param obj
	 * @return
	 */
	public HashMap<String,Object> selectRepeat(Object obj);
	
	
	/**
	 * 如果返回多条记录则会报错
	 * 两字段去重
	 * @param obj
	 * @return
	 */
	public HashMap<String,Object> selectRepeatTowColumn(Object obj);

	/**
	 * 获取一个表中,其中一个字段的最大值
	* @Title: getMaxValue 
	* @Description: TODO
	* @author:罗凯
	* @param tableName
	* @param column
	* @return    
	* String    返回类型 
	* @date 2016年8月22日 上午10:51:03 
	* @throws
	 */
	public String selectMaxValue(@Param("tableName")String tableName,@Param("column") String column);
	
	
}