package com.zkingsoft.services.bus;

import com.zkingsoft.pojo.PaginationVO;
import java.util.List;
import com.zkingsoft.model.bus.BusCatalog;
import com.zkingsoft.constraint.BaseServices;

/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-28 16:55
 */
public interface BusCatalogService  extends BaseServices<BusCatalog>{
	
	/**
	 * 新增BusCatalog
	 * 
	 */
	public int add(BusCatalog busCatalog);
   	
   	/**
	 * 批量新增BusCatalog
	 * 
	 */
	public int batchAdd(List<BusCatalog>  busCatalogList);
   	
   	/**
	 * 根据map键值对 更新BusCatalog
	 * 
	 */
	public int modifyByMap(BusCatalog oldBusCatalog ,BusCatalog newBusCatalog);
	
	/**
	 * 根据对象 更新BusCatalog
	 * 
	 */
	public int modifyByModel(BusCatalog busCatalog);
	
	/**
	 * 批量删除BusCatalog
	 * 
	 */
	public int remove(List<Long> list);

	/**
	 * 根据id删除BusCatalog
	 * 
	 */
	public int removeById(Long cataId);
	
	/**
	 * 根据对象删除BusCatalog
	 * 
	 */
	public int removeByModel(BusCatalog busCatalog);
	
	/**
	 * 分页查询BusCatalog
	 * 
	 */
	public List<BusCatalog> findInPage(BusCatalog busCatalog, PaginationVO pageVo);

	/**
	 * 根据对象查询BusCatalog
	 * 
	 */
	public List<BusCatalog> findByModel(BusCatalog busCatalog);
	
	/**
	 * 统计记录数BusCatalog
	 * 
	 */
	public int  findTotal(BusCatalog busCatalog);
	
	/**
	 * 根据id查询BusCatalog
	 * 
	 */
	public BusCatalog  findById(Long cataId);

   	
 
  
}