package com.zkingsoft.services.bus.impl;

import java.util.List;

import org.apache.commons.lang.NotImplementedException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.zkingsoft.dao.bus.BusAreaDao;
import com.zkingsoft.model.bus.BusArea;
import com.zkingsoft.pojo.PaginationVO;
import com.zkingsoft.services.bus.BusAreaService;

/**
 * This field was generated by Zking.software.Codegen.
 * 
 * @date 2016-11-28 16:55
 */
@Service("busAreaService")
public class BusAreaServiceImpl implements BusAreaService {

	@Autowired
	private BusAreaDao busAreaDao;
	
	@Override
	public int add(BusArea obje) {
		throw new NotImplementedException();
	}

	@Override
	public int batchAdd(List<BusArea> obje) {
		throw new NotImplementedException();
	}

	@Override
	public int modifyByMap(BusArea oldValue, BusArea newValue) {
		throw new NotImplementedException();
	}

	@Override
	public int remove(List<Long> list) {
		throw new NotImplementedException();
	}

	@Override
	public int removeById(Long id) {
		throw new NotImplementedException();
	}

	@Override
	public List<BusArea> findInPage(BusArea obje, PaginationVO pageVo) {
		throw new NotImplementedException();
	}

	@Override
	public List<BusArea> findByModel(BusArea obje) {
		throw new NotImplementedException();
	}

	@Override
	public int findTotal(BusArea obje) {
		throw new NotImplementedException();
	}

	@Override
	public BusArea findById(Long id) {
		throw new NotImplementedException();
	}

	@Override
	public List<BusArea> findChildArea(Long parentId) {
		return busAreaDao.selectChildrenArea(parentId);
	}

}