package com.zkingsoft.dao.web;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import java.util.List;
import com.zkingsoft.model.web.WebArticle;
import java.util.Map;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-01 10:36
 */


public interface WebArticleDao{

	public int insert(WebArticle webArticle);
   	
   	public int batchInsert(@Param("list") List<WebArticle> webArticleList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(WebArticle webArticle);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long artId);

	public int deleteByModel(@Param("record") WebArticle webArticle);
	
	public List<WebArticle> selectInPage(@Param("record") WebArticle webArticle, @Param("pageVo") PaginationVO pageVo);

	public List<WebArticle> selectByModel(@Param("record") WebArticle webArticle);
	
	public int  selectTotalRecord(@Param("record") WebArticle webArticle);
	
	public WebArticle  selectById(Long artId);
	
	public WebArticle  selectForUpdate(Long artId);
	
}