package com.zkingsoft.dao.web;

import org.apache.ibatis.annotations.Param;
import com.zkingsoft.pojo.PaginationVO;
import java.util.List;
import com.zkingsoft.model.web.WebNav;
import java.util.Map;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-11-28 15:35
 */


public interface WebNavDao{

	public int insert(WebNav webNav);
   	
   	public int batchInsert(@Param("list") List<WebNav> webNavList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(WebNav webNav);
	
	public int deleteByIds(@Param("list") List<Long> list);
	
	public int deleteById(Long navId);

	public int deleteByModel(@Param("record") WebNav webNav);
	
	public List<WebNav> selectInPage(@Param("record") WebNav webNav, @Param("pageVo") PaginationVO pageVo);

	public List<WebNav> selectByModel(@Param("record") WebNav webNav);
	
	public int  selectTotalRecord(@Param("record") WebNav webNav);
	
	public WebNav  selectById(Long navId);
	
	public WebNav  selectForUpdate(Long navId);
	
}